### ISSUE TITLE
dup "maven-jar-plugin" configuration in pom.xml

### ISSUE THREAD

**Issue by ghost** [italia/anpr-client-example#1]
running "mvn clean install" as per instructions throws the following warning:

```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for it.interno.anpr:tool-testconn:jar:1.3.0
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-jar-plugin @ line 347, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 347, column 12
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
```

Indeed, the "maven-jar-plugin" is configured twice, once at line 155:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<configuration>
		<archive>
			<manifest>
				<addClasspath>true</addClasspath>
				<classpathPrefix>lib/</classpathPrefix>
				<mainClass>it.interno.anpr.security.main.RunSenderMessage</mainClass>
			</manifest>
		</archive>
	</configuration>
</plugin>
```
and then at line 347:

```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-jar-plugin</artifactId>
	<configuration>
		<archive>
			<manifest>
				<addClasspath>true</addClasspath>
				<mainClass>it.interno.anpr.testconn.gui.GUIFrame</mainClass>
			</manifest>
		</archive>
	</configuration>
</plugin>	
```

there can be [just one main class declared in the manifest](https://docs.oracle.com/javase/tutorial/deployment/jar/appman.html), right?

**PS**: also running "mvn clean install" without the certificate configured makes the tests fail:

```
...
test4_3002OnFree(it.sogei.ws.client.ConnessioneFreeTest)  Time elapsed: 0.438 sec  <<< ERROR!
java.lang.RuntimeException: javax.xml.ws.soap.SOAPFaultException: Security processing failed.
	at it.sogei.ws.client.ConnessioneFreeTest.test4_3002OnFree(ConnessioneFreeTest.java:47)
Caused by: javax.xml.ws.soap.SOAPFaultException: Security processing failed.
	at it.sogei.ws.client.ConnessioneFreeTest.test4_3002OnFree(ConnessioneFreeTest.java:47)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: WSHandler: cannot create instance of callback handler: it.interno.anpr.security.saml.SAML2CallbackHandler
	at it.sogei.ws.client.ConnessioneFreeTest.test4_3002OnFree(ConnessioneFreeTest.java:47)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: Cannot create Crypto class null
	at it.sogei.ws.client.ConnessioneFreeTest.test4_3002OnFree(ConnessioneFreeTest.java:47)
Caused by: org.apache.wss4j.common.ext.WSSecurityException: Proxy file (keystore/FREE/<Nome file keystore>.p12) not found.
	at it.sogei.ws.client.ConnessioneFreeTest.test4_3002OnFree(ConnessioneFreeTest.java:47)
Caused by: java.io.FileNotFoundException: keystore/FREE/<Nome file keystore>.p12 (No such file or directory)
	at it.sogei.ws.client.ConnessioneFreeTest.test4_3002OnFree(ConnessioneFreeTest.java:47)


Results :

Tests in error: 
  ConnessioneFreeTest.test1_ConnessioneOnFree:35 » Runtime javax.xml.ws.soap.SOA...
  ConnessioneFreeTest.test4_3002OnFree:47 » Runtime javax.xml.ws.soap.SOAPFaultE...

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:06 min
[INFO] Finished at: 2018-05-24T12:26:24+02:00
[INFO] Final Memory: 43M/477M
[INFO] ------------------------------------------------------------------------
```

Maybe worth warning about that in the README.

Cheers,
Corrado.

**Comment by gife67** [comment]
Hi,
you're right. There are two alternative ways to use the client. it is preferable to use the command line (RunSenderMessage). I add a block comment for the other mode.
The keystore is distributed separately and the properties file must be correctly setup, before the build can run with the execution of the tests.
Thanks,
Giuseppe

**Comment by ruphy** [comment]
Thanks a lot @corradocampisano for reporting this issue :+1:
