### ISSUE TITLE
Personalizzazione per ambienti TEST e PROD

### ISSUE THREAD

**Issue by Eduardo1977** [italia/anpr-client-example#9]
E' possibile personalizzare il client per eseguire richieste verso le varie tipologie di Servizi per i diversi
ambienti a disposizione (Test, Presubentro e Produzione) ?

Ho provato iniziando ad aggiungere la cartella TEST (con il relativo certificato dell'ambiente di test di Bistagno AL) in KEYSTORE.
Ho aggiunto anche i relativi file "TEST_Keystore.properties" e "PRE_Keystore.properties" in "src/main/resources/config".  
Ma provando a compilare tramite "mvn clean install" mi dà errore:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.203 s
[INFO] Finished at: 2018-09-12T17:51:56+02:00
[INFO] Final Memory: 41M/317M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19:test (default-test) on project tool-testconn: There are test failures.

...
....
.....

**Comment by Eduardo1977** [comment]
Stamattina ho modificato il file "ConnessioneFreeTest.java" eliminando le chiamate verso l'ambiente FREE e inserendone alcune verso TEST e PRE. 
Adesso riesco a compilare il client senza errori. 
Ora vediamo se riesco a fare qualche chiamata verso i vari servizi 3000, 6001, ...

**Comment by gife67** [comment]
Ciao Eduardo,
da quello che viene riportato sulla build (solo la parte finale), questa fallisce perchè uno o più unit test sono falliti, occorrerebbe verificare l'errore che viene preso. Nel caso si voglia solo eseguire la build, per ottenere l'artifact (jar), senza eseguire gli unit test, lo si può fare eseguendo il comando:
mvn clean install -DskipTests
Ti confermo che la versione pubblicata permette la gestione di tutti gli ambienti ANPR. L'ambiente con cui lavorare è comandato tramite la classe EnvironmentHandler settando opportunamente l'attributo specifico.

**Comment by Eduardo1977** [comment]
Buongiorno Giuseppe,
grazie per il suggerimento che userò sicuramente la prossima volta. 
Adesso volevo testare il client per fare qualche chiamata usando il vecchio modo (prima versione 1.0.0) da linea di comando ma non funziona "runClient PRE WS3002 request\3002\3002_XXXXXX_PRE.req",  dove runClient.cmd contiene l'istruzione: java -cp tool-testconn-1.3.0.jar;. it.interno.anpr.security.main.RunSenderMessage %1 %2 %3

Funziona ancora così?

**Comment by gife67** [comment]
Ti confermo che la linea di comando è corretta, ovviamente deve essere presente il jar specificato nella stessa directory di dove hai lo script .cmd
Se usi il client a linea di comando e gestisci tutti i file necessari all'esterno del jar (config, keystore, request), devi assicurati di togliere dal jar la directory config, che la build inserisce poichè presente in src/main/resources, essendo utilizzata per l'esecuzione degli unit test. Sempre che sia questo il problema. Se alleghi l'errore che stai riscontrando posso aiutarti meglio.

**Comment by Eduardo1977** [comment]
Il .jar sta insieme al .cmd

L'errore è il seguente:
Exception in thread "main" java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
        at it.interno.anpr.activator.DispatchHandler.execute(DispatchHandler.java:79)
        at it.interno.anpr.security.main.RunSenderMessage.main(RunSenderMessage.java:62)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

Mi manca la cartella "lib" con le librerie di crittografia BouncyCastle (e non solo) ? Da dove la copio?

**Comment by gife67** [comment]
La "lib" puoi prenderla dal client che utilizzavi relativo alla 1.0.0 oppure tutti i jar necessari li hai nel repository maven locale (.m2) sotto la directory della tua utenza di sistema. Sicuramente reperirli dal repository maven può risultare leggermente più complicato poichè sono circa 70 jar.

**Comment by Eduardo1977** [comment]
PS C:\Users\GiraE\workspace\anpr-client-example-master> .\runClient PRE WS3002 request\3002\3002_006017_PRE_testLegame3.req

C:\Users\GiraE\workspace\anpr-client-example-master>java -cp tool-testconn-1.3.0.jar;. it.interno.anpr.security.main.RunSenderMessage PRE WS3002 request\3002\3002_006017_PRE_testLegame3.req
log4j:WARN Continuable parsing error 16 and column 44
log4j:WARN Dichiarare l'attributo "additivity" per il tipo di elemento "level".
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Retreiving an instance of org.apache.log4j.Logger.
log4j: Setting [it.interno.anpr] additivity to [false].
log4j: Level value for it.interno.anpr is  [DEBUG].
log4j: it.interno.anpr level set to DEBUG
log4j: Class name: [org.apache.log4j.ConsoleAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n].
log4j: Adding appender named [console] to category [it.interno.anpr].
log4j: Level value for root is  [INFO].
log4j: root level set to INFO
log4j: Adding appender named [console] to category [root].
2018-09-13 12:29:33 INFO  BusApplicationContext:510 - Refreshing org.apache.cxf.bus.spring.BusApplicationContext@65e2dbf3: startup date [Thu Sep 13 12:29:33 CEST 2018]; root of context hierarchy
2018-09-13 12:29:33 INFO  BusApplicationContext:449 - Loaded configuration file cxf.xml.
2018-09-13 12:29:33 INFO  ControlledValidationXmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [META-INF/cxf/cxf.xml]
2018-09-13 12:29:33 INFO  ControlledValidationXmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [cxf.xml]
2018-09-13 12:29:34 INFO  ReflectionServiceFactoryBean:390 - Creating Service {http://sogei.it/ANPR/3000AnprService}AnprService3000 from WSDL: jar:file:/C:/Users/GiraE/workspace/anpr-client-example-master/tool-testconn-1.3.0.jar!/wsdl/
3000serviziConsultazione.wsdl
2018-09-13 12:29:35 ERROR Op3002Handler:43 - Exception nell'invio richiesta
java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Unknown Source)
        at java.util.Properties.load0(Unknown Source)
        at java.util.Properties.load(Unknown Source)
        at it.interno.anpr.config.ConfigHandler.getProp(ConfigHandler.java:43)
        at it.interno.anpr.config.ConfigHandler.getParam(ConfigHandler.java:64)
        at it.interno.anpr.security.message.RequestHandler.setClient(RequestHandler.java:57)
        at it.interno.anpr.security.message.Op3002Handler.sendRequest(Op3002Handler.java:34)
        at it.interno.anpr.activator.DispatchHandler.execute(DispatchHandler.java:80)
        at it.interno.anpr.security.main.RunSenderMessage.main(RunSenderMessage.java:62)
java.lang.RuntimeException: java.lang.NullPointerException
        at it.interno.anpr.security.message.Op3002Handler.sendRequest(Op3002Handler.java:44)
        at it.interno.anpr.activator.DispatchHandler.execute(DispatchHandler.java:80)
        at it.interno.anpr.security.main.RunSenderMessage.main(RunSenderMessage.java:62)
Caused by: java.lang.NullPointerException
        at java.util.Properties$LineReader.readLine(Unknown Source)
        at java.util.Properties.load0(Unknown Source)
        at java.util.Properties.load(Unknown Source)
        at it.interno.anpr.config.ConfigHandler.getProp(ConfigHandler.java:43)
        at it.interno.anpr.config.ConfigHandler.getParam(ConfigHandler.java:64)
        at it.interno.anpr.security.message.RequestHandler.setClient(RequestHandler.java:57)
        at it.interno.anpr.security.message.Op3002Handler.sendRequest(Op3002Handler.java:34)
        ... 2 more

**Comment by Eduardo1977** [comment]
Ho copiato la lib dal vecchio 1.0.0

**Comment by gife67** [comment]
sembrerebbe esserci un problema con il file di Properties, che dovrebbe essere posizionato nella directory config con il nome PRE_Keystore.properties e con un contenuto simile a questo:

# Properties WSS4J - Keystore del Comune
org.apache.ws.security.crypto.merlin.keystore.file=keystore/001122-PC-0001.p12
org.apache.ws.security.crypto.merlin.keystore.password=1234
org.apache.ws.security.crypto.merlin.keystore.type=pkcs12
org.apache.ws.security.crypto.merlin.keystore.alias=001122-PC-0001

# Properties internal
ID_OPERATORE=CCCAAA11A28A111A
ID_SEDE=001122
ID_POSTAZIONE=001122-PC-0001 
ID_APPLICAZIONE=12345
ID_TRANSAZIONE=99999
PATH_KEYSTORE_POSTAZIONE=keystore/001122-PC-0001.p12
PASS_KEYSTORE_POSTAZIONE=1234
ALIAS_KEYSTORE_POSTAZIONE=001122-PC-0001
URL_WS=https://wspre.anpr.interno.it

ovviamente opportunamente valorizzato con i dati del certificato del Comune.

Inoltre se stai utilizzando i WSDL pubblicati sul portale ANPR, devi modificarli per aggiungere ad ogni operation la direttiva per l'utilizzo della policy:
		<wsdl:operation name="interrogazioneCittadino_famiglia_convivenza">      
			<wsdlsoap:operation soapAction=""/>      
			<wsdl:input>        
				**<wsp:PolicyReference xmlns:wsp="http://www.w3.org/ns/ws-policy" URI="policy-X509v3.xml"/>** 
				<wsdlsoap:body use="literal"/>      
			</wsdl:input>      
			<wsdl:output>        
				<wsdlsoap:body use="literal"/>      
			</wsdl:output>   
		</wsdl:operation>

**Comment by Eduardo1977** [comment]
Grazie mille!
Ho ripulito la repository e compilato con "mvn clean install -DskipTests". Così ha funzionato.
Ho già utilizzato il .jar per testare il ws3002 con alcuni casi che mi interessavano.
Buona giornata

**Comment by gife67** [comment]
Bene, 
perfetto 👍 
Buona giornata
